const REQUEST_POSTS = "REQUEST_POSTS",
      RECEIVE_POSTS = "RECEIVE_POSTS",
      INCREASE_COUNT_POSTS = "INCREASE_COUNT_POSTS",
      SEARCH_POST = "SEARCH_POST";

export default {
    REQUEST_POSTS,
    RECEIVE_POSTS,
    INCREASE_COUNT_POSTS,
    SEARCH_POST
};